# github action file created
name: 🚀 Deploy website on push
#run on trigger manually:
on: workflow_dispatch
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    - name: Print environment variables
      run: |
        echo "FTP Server: ${{ secrets.ftp_server }}"
        echo "FTP Username: ${{ secrets.ftp_username }}"
        echo "FTP Password: ${{ secrets.ftp_password }}"
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.ftp_server }}
        username: ${{ secrets.ftp_username }}
        password: ${{ secrets.ftp_password }}
